services:
  - type: web
    name: wanderlust-app
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: wanderlust_db
          property: connectionString
      - key: PORT
        value: 4001
      - key: TRUSTED_ORIGINS
        value: https://wanderlust-app.onrender.com

databases:
  - name: wanderlust_db
    databaseName: wanderlust
    user: wanderlust_user

